FROM node:13.12.0-alpine as build
WORKDIR /home/app
COPY . .
RUN npm ci && npm cache clean --force
RUN npm run build

FROM nginx:stable-alpine
# COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /home/app/build /usr/share/nginx/html

COPY .env /docker-entrypoint.d

RUN chmod +x /docker-entrypoint.d/.env

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
