@url = http://localhost:8080/api/user

POST  {{url}}/restaurant HTTP/1.1
Content-Type: application/json 

{

    "username": "john@sh.com",
    "password": "P@ssw0rd!",
    "roles": ["OWNER"]

}

@second = http://localhost:8080/api/restaurants
###

POST {{second}} HTTP/1.1
Content-Type: application/json

{
    "name": "name",
    "userId": 4,
    "timeEstimate": 12,
    "address": "john@sh.com"
}
