@url = http://localhost:8090/api/restaurant/queue


###
POST  http://localhost:8090/api/user/customer HTTP/1.1
Content-Type: application/json 

{

    "username": "john@sh.com",
    "password": "P@ssw0rd!",
    "roles": ["CUSTOMER"]

}
###
POST  http://localhost:8090/api/authenticate/login HTTP/1.1
Content-Type: application/json 

{

    "username": "john@sh.com",
    "password": "P@ssw0rd!"

}

###
POST  {{url}} HTTP/1.1
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJxdWVyayIsInN1YiI6ImpvaG5Ac2guY29tIiwianRpIjoiNCIsImF1dGhvcml0aWVzIjoiUk9MRV9DVVNUT01FUiIsImV4cCI6MTY1MjExMzc5Nn0.PsW4pgOVaA6JF-3JK2j36tAxCo8qp5OIrwhMqaovsgY

{

    "customerId": 1,
    "restaurantId": 1,
    
    "orderedAhead": true,
    "expired": false

}